mod: chatops
branchName: '${issue.number}-${issue.title}'
branches:
  - label:
      - 프로젝트 세팅
      - 기능 개발
    prefix: feature/
    prTarget: feature

  - label: chore
    prefix: chore/
    prTarget: chore

  - label: bug
    prefix: fix/
    prTarget: fix
    
autoCloseIssue: true
