branchName: '${issue.number}_${issue.title}'
commentMessage: 'Branch ${branchName} created!'
branches:
  - label: [setting, feature]
    prefix: feature/
    prTarget: feature

  - label: chore
    prefix: chore/
    prTarget: chore

  - label: bug
    prefix: fix/
    prTarget: fix
    
autoCloseIssue: true
