branchName: '${issue.number}-${issue.title}'
commentMessage: 'Branch ${branchName} created!'
branches:
  - label:
      - "프로젝트 세팅"
      - "기능 개발"
    prefix: feature/
    prTarget: feature

  - label: chore
    prefix: chore/
    prTarget: chore

  - label: bug
    prefix: fix/
    prTarget: fix
    
autoCloseIssue: true
